version: '3'
services:
  first_python:
    build: ./first_python
    volumes:
      - ./first_python:/app
    ports:
      - 5000:5000
  jaeger:
    image: jaegertracing/all-in-one:1.21
    ports:
      - 6831:6831/udp
      - 16686:16686
